from datetime import datetime, timedelta

from backend.app.core.config import settings
from backend.app.core.security import create_access_token
from backend.app.database.models import CouponCode, User
from backend.app.services.coupons import create_coupon


def _make_user(db, username, is_admin=False, credits=0):
    user = User(
        username=username,
        email=f"{username}@example.com",
        password_hash="x",
        is_admin=is_admin,
        credit_balance=credits,
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


def _login(client, user):
    token = create_access_token(str(user.id))
    client.cookies.set(settings.COOKIE_NAME, token)


def test_redeem_valid_coupon_grants_credits(client, db):
    user = _make_user(db, "redeemer")
    create_coupon(db, credits=7, code="LAUNCH7")
    db.commit()
    _login(client, user)

    response = client.post("/api/credits/redeem", data={"code": "launch7"})
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["credits_granted"] == 7
    assert body["credit_balance"] == 7


def test_redeem_same_coupon_twice_fails(client, db):
    user = _make_user(db, "doubledip")
    create_coupon(db, credits=3, code="ONCE")
    db.commit()
    _login(client, user)

    assert client.post("/api/credits/redeem", data={"code": "ONCE"}).status_code == 200
    response = client.post("/api/credits/redeem", data={"code": "ONCE"})
    assert response.status_code == 400
    assert "already redeemed" in response.json()["detail"]


def test_redeem_expired_coupon_fails(client, db):
    user = _make_user(db, "latecomer")
    create_coupon(
        db,
        credits=3,
        code="EXPIRED",
        expires_at=datetime.utcnow() - timedelta(days=1),
    )
    db.commit()
    _login(client, user)

    response = client.post("/api/credits/redeem", data={"code": "EXPIRED"})
    assert response.status_code == 400
    assert "expired" in response.json()["detail"]


def test_redeem_inactive_and_unknown_codes_fail(client, db):
    user = _make_user(db, "hopeful")
    coupon = create_coupon(db, credits=3, code="PAUSED")
    coupon.is_active = False
    db.commit()
    _login(client, user)

    assert client.post("/api/credits/redeem", data={"code": "PAUSED"}).status_code == 400
    assert client.post("/api/credits/redeem", data={"code": "NEVEREXISTED"}).status_code == 400


def test_redeem_respects_max_redemptions(client, db):
    create_coupon(db, credits=2, code="LIMIT1", max_redemptions=1)
    db.commit()

    first = _make_user(db, "firstuser")
    _login(client, first)
    assert client.post("/api/credits/redeem", data={"code": "LIMIT1"}).status_code == 200

    second = _make_user(db, "seconduser")
    _login(client, second)
    response = client.post("/api/credits/redeem", data={"code": "LIMIT1"})
    assert response.status_code == 400
    assert "redemption limit" in response.json()["detail"]


def test_redeem_requires_auth(client, db):
    response = client.post("/api/credits/redeem", data={"code": "ANY"})
    assert response.status_code == 401


def test_founder_page_requires_admin(client, db):
    user = _make_user(db, "civilian")
    _login(client, user)
    assert client.get("/admin/founder").status_code == 403


def test_founder_page_renders_for_admin(client, db):
    admin = _make_user(db, "founder", is_admin=True)
    create_coupon(db, credits=5, code="SHOWME")
    db.commit()
    _login(client, admin)

    response = client.get("/admin/founder")
    assert response.status_code == 200
    assert "Founder Console" in response.text
    assert "SHOWME" in response.text


def test_founder_creates_coupon_with_autogenerated_code(client, db):
    admin = _make_user(db, "founder2", is_admin=True)
    _login(client, admin)

    response = client.post(
        "/admin/founder/coupons",
        data={"credits": "10", "code": "", "max_redemptions": "5", "expires_on": "", "note": "test"},
        follow_redirects=False,
    )
    assert response.status_code == 303
    coupon = db.query(CouponCode).first()
    assert coupon is not None
    assert coupon.credits == 10
    assert coupon.max_redemptions == 5
    assert coupon.code.startswith("PXNN-")


def test_founder_grants_credits_by_username(client, db):
    admin = _make_user(db, "founder3", is_admin=True)
    target = _make_user(db, "luckyfan", credits=1)
    _login(client, admin)

    response = client.post(
        "/admin/founder/credits",
        data={"username": "luckyfan", "amount": "9"},
        follow_redirects=False,
    )
    assert response.status_code == 303
    db.refresh(target)
    assert target.credit_balance == 10


def test_founder_toggle_and_delete_coupon(client, db):
    admin = _make_user(db, "founder4", is_admin=True)
    coupon = create_coupon(db, credits=2, code="TOGGLEME")
    db.commit()
    _login(client, admin)

    client.post(f"/admin/founder/coupons/{coupon.id}/toggle", follow_redirects=False)
    db.refresh(coupon)
    assert coupon.is_active is False

    client.post(f"/admin/founder/coupons/{coupon.id}/delete", follow_redirects=False)
    assert db.query(CouponCode).filter(CouponCode.id == coupon.id).first() is None


def test_founder_updates_platform_settings(client, db):
    admin = _make_user(db, "founder5", is_admin=True)
    _login(client, admin)

    response = client.post(
        "/admin/founder/settings",
        data={
            "trial_credits": "3",
            "max_upload_files": "50",
            "max_upload_file_mb": "100",
            "max_upload_batch_mb": "500",
            "allowed_upload_extensions": "mp3, wav, .FLAC",
        },
        follow_redirects=False,
    )
    assert response.status_code == 303

    from backend.app.services.site_settings import get_setting

    assert get_setting(db, "trial_credits", "") == "3"
    assert get_setting(db, "max_upload_files", "") == "50"
    assert get_setting(db, "allowed_upload_extensions", "") == "mp3,wav,flac"
